# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\inclu\Documents\Work\GitHub\orion-counter-card\qtdesigner\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1428, 1018)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("border-radius: 10px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.l_BackgroundA = QtWidgets.QLabel(self.centralwidget)
        self.l_BackgroundA.setGeometry(QtCore.QRect(50, 70, 711, 851))
        self.l_BackgroundA.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0,0,0,255), stop:1 rgba(40,40,40,255));\n"
"border-radius:20px;")
        self.l_BackgroundA.setText("")
        self.l_BackgroundA.setObjectName("l_BackgroundA")
        self.l_BackgroundB = QtWidgets.QLabel(self.centralwidget)
        self.l_BackgroundB.setGeometry(QtCore.QRect(650, 80, 731, 821))
        self.l_BackgroundB.setStyleSheet("background-color: rgb(255,255,255);\n"
"border-radius: 20px;")
        self.l_BackgroundB.setText("")
        self.l_BackgroundB.setObjectName("l_BackgroundB")
        self.l_Title = QtWidgets.QLabel(self.centralwidget)
        self.l_Title.setGeometry(QtCore.QRect(70, 860, 251, 71))
        self.l_Title.setObjectName("l_Title")
        self.Img_Profile = QtWidgets.QLabel(self.centralwidget)
        self.Img_Profile.setGeometry(QtCore.QRect(280, 270, 251, 271))
        self.Img_Profile.setStyleSheet("border-image: url(:/none_avatar/avatar_none.jpg);\n"
"border-radius: 40px;")
        self.Img_Profile.setText("")
        self.Img_Profile.setObjectName("Img_Profile")
        self.l_Name = QtWidgets.QLabel(self.centralwidget)
        self.l_Name.setGeometry(QtCore.QRect(340, 550, 141, 31))
        self.l_Name.setObjectName("l_Name")
        self.l_Status = QtWidgets.QLabel(self.centralwidget)
        self.l_Status.setGeometry(QtCore.QRect(690, 880, 41, 21))
        self.l_Status.setObjectName("l_Status")
        self.l_Result = QtWidgets.QLabel(self.centralwidget)
        self.l_Result.setGeometry(QtCore.QRect(340, 580, 141, 61))
        self.l_Result.setObjectName("l_Result")
        self.l_Icon_Description = QtWidgets.QLabel(self.centralwidget)
        self.l_Icon_Description.setGeometry(QtCore.QRect(950, 120, 241, 211))
        self.l_Icon_Description.setStyleSheet("border-image: url(:/proxy_step/proxy step.png);\n"
"border-radius: 20px;")
        self.l_Icon_Description.setText("")
        self.l_Icon_Description.setObjectName("l_Icon_Description")
        self.l_Description = QtWidgets.QLabel(self.centralwidget)
        self.l_Description.setGeometry(QtCore.QRect(800, 350, 541, 61))
        self.l_Description.setObjectName("l_Description")
        self.l_Time = QtWidgets.QLabel(self.centralwidget)
        self.l_Time.setGeometry(QtCore.QRect(290, 130, 221, 51))
        self.l_Time.setObjectName("l_Time")
        self.l_Input_ID = QtWidgets.QTextEdit(self.centralwidget)
        self.l_Input_ID.setGeometry(QtCore.QRect(790, 850, 571, 41))
        self.l_Input_ID.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"border-radius: 20px;")
        self.l_Input_ID.setObjectName("l_Input_ID")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(790, 420, 571, 421))
        self.label.setStyleSheet("background-color: rgb(241, 241, 241);\n"
"border-radius: 20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.l_BackgroundB.raise_()
        self.l_BackgroundA.raise_()
        self.l_Title.raise_()
        self.Img_Profile.raise_()
        self.l_Name.raise_()
        self.l_Status.raise_()
        self.l_Result.raise_()
        self.l_Icon_Description.raise_()
        self.l_Description.raise_()
        self.l_Time.raise_()
        self.l_Input_ID.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("color: rgb(255, 255, 255);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Counter Cards"))
        self.l_Title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">Столовая <br/></span><span style=\" font-size:12pt; font-weight:600; text-decoration: underline; color:#ffffff;\">АО &quot;АзияАгроФуд&quot;</span></p><p><span style=\" font-size:12pt; color:#ffffff;\"><br/></span></p></body></html>"))
        self.l_Name.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Name Surname</span></p></body></html>"))
        self.l_Status.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#11ff4c;\">Status</span></p></body></html>"))
        self.l_Result.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#11ff4c;\">Result</span></p></body></html>"))
        self.l_Description.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Поднесите свой рабочий пропуск к считывателю.</span><span style=\" font-size:14pt;\"/><span style=\" font-size:12pt;\"><br/>После писка, будет выписан один обед в столовой.</span></p></body></html>"))
        self.l_Time.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\">Time</span></p><p align=\"center\"><br/></p></body></html>"))
        self.l_Input_ID.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:10px;\"><span style=\" font-size:14pt;\">Поднесите пропуск к прокси считывателю.</span></p></body></html>"))
import resources_rc
