# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources, sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        self.MainApps = QtWidgets.QWidget(MainWindow)
        self.MainApps.setObjectName("MainApps")
        self.MainWindow_2 = QtWidgets.QVBoxLayout(self.MainApps)
        self.MainWindow_2.setObjectName("MainWindow_2")
        self.Main = QtWidgets.QWidget(self.MainApps)
        self.Main.setObjectName("Main")
        self.Main_2 = QtWidgets.QVBoxLayout(self.Main)
        self.Main_2.setSpacing(0)
        self.Main_2.setObjectName("Main_2")
        self.Header = QtWidgets.QWidget(self.Main)
        self.Header.setStyleSheet("border-image: url(:/background_header/background_forest.jpg) 0 0 0 0 stretch stretch;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0,0,0,80), stop:1 rgba(40,40,40,80));\n"
"border-top-left-radius:50px;")
        self.Header.setObjectName("Header")
        self.gridLayout = QtWidgets.QGridLayout(self.Header)
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setObjectName("gridLayout")
        self.Layout_Profile = QtWidgets.QWidget(self.Header)
        self.Layout_Profile.setStyleSheet("background: None;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 180), stop:1 rgba(0, 0, 0, 60));\n"
"border-bottom-left-radius: 60px;\n"
"border-image: None;")
        self.Layout_Profile.setObjectName("Layout_Profile")
        self.Layout_Profile_2 = QtWidgets.QHBoxLayout(self.Layout_Profile)
        self.Layout_Profile_2.setObjectName("Layout_Profile_2")
        self.Img_Profile = QtWidgets.QLabel(self.Layout_Profile)
        self.Img_Profile.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Img_Profile.setAutoFillBackground(False)
        self.Img_Profile.setStyleSheet("border-image: url(:/none_avatar/avatar_none.jpg);\n"
"border-radius: 100px;")
        self.Img_Profile.setText("")
        self.Img_Profile.setObjectName("Img_Profile")
        self.Layout_Profile_2.addWidget(self.Img_Profile)
        self.Layout_Name = QtWidgets.QVBoxLayout()
        self.Layout_Name.setContentsMargins(10, 10, 10, 10)
        self.Layout_Name.setObjectName("Layout_Name")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Layout_Name.addItem(spacerItem)
        self.l_Name = QtWidgets.QLabel(self.Layout_Profile)
        self.l_Name.setStyleSheet("Background: None;")
        self.l_Name.setObjectName("l_Name")
        self.Layout_Name.addWidget(self.l_Name)
        self.l_Result = QtWidgets.QLabel(self.Layout_Profile)
        self.l_Result.setStyleSheet("Background: None;")
        self.l_Result.setObjectName("l_Result")
        self.Layout_Name.addWidget(self.l_Result)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Layout_Name.addItem(spacerItem1)
        self.Layout_Profile_2.addLayout(self.Layout_Name)
        self.Layout_Profile_2.setStretch(0, 5)
        self.Layout_Profile_2.setStretch(1, 20)
        self.gridLayout.addWidget(self.Layout_Profile, 0, 0, 1, 1)
        self.Layout_CounterUser = QtWidgets.QWidget(self.Header)
        self.Layout_CounterUser.setStyleSheet("background: None;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 60), stop:1 rgba(0, 0, 0, 180));\n"
"border-radius: 0;\n"
"border-image: None;")
        self.Layout_CounterUser.setObjectName("Layout_CounterUser")
        self.Layout_CounterUser_2 = QtWidgets.QGridLayout(self.Layout_CounterUser)
        self.Layout_CounterUser_2.setContentsMargins(-1, 10, 10, -1)
        self.Layout_CounterUser_2.setObjectName("Layout_CounterUser_2")
        self.l_Title = QtWidgets.QLabel(self.Layout_CounterUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_Title.sizePolicy().hasHeightForWidth())
        self.l_Title.setSizePolicy(sizePolicy)
        self.l_Title.setMinimumSize(QtCore.QSize(20, 20))
        self.l_Title.setStyleSheet("Background: none")
        self.l_Title.setObjectName("l_Title")
        self.Layout_CounterUser_2.addWidget(self.l_Title, 0, 0, 1, 1)
        self.l_CounterUsers = QtWidgets.QLabel(self.Layout_CounterUser)
        self.l_CounterUsers.setMinimumSize(QtCore.QSize(20, 20))
        self.l_CounterUsers.setStyleSheet("Background: None;")
        self.l_CounterUsers.setObjectName("l_CounterUsers")
        self.Layout_CounterUser_2.addWidget(self.l_CounterUsers, 2, 0, 1, 1)
        self.l_Status = QtWidgets.QLabel(self.Layout_CounterUser)
        self.l_Status.setMinimumSize(QtCore.QSize(20, 20))
        self.l_Status.setStyleSheet("Background: None")
        self.l_Status.setObjectName("l_Status")
        self.Layout_CounterUser_2.addWidget(self.l_Status, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Layout_CounterUser_2.addItem(spacerItem2, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.Layout_CounterUser, 0, 1, 1, 1)
        self.Layout_Description = QtWidgets.QWidget(self.Header)
        self.Layout_Description.setStyleSheet("background: None;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 180), stop:1 rgba(0, 0, 0, 60));\n"
"border-bottom-left-radius: 60px;\n"
"border-top-left-radius: 40px;\n"
"border-image: None;")
        self.Layout_Description.setObjectName("Layout_Description")
        self.Layout_Description_2 = QtWidgets.QGridLayout(self.Layout_Description)
        self.Layout_Description_2.setContentsMargins(10, 10, 10, 10)
        self.Layout_Description_2.setObjectName("Layout_Description_2")
        self.l_Icon_Description = QtWidgets.QLabel(self.Layout_Description)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_Icon_Description.sizePolicy().hasHeightForWidth())
        self.l_Icon_Description.setSizePolicy(sizePolicy)
        self.l_Icon_Description.setMinimumSize(QtCore.QSize(160, 120))
        self.l_Icon_Description.setStyleSheet("border-image: url(:/proxy_step/proxy step.png);\n"
"border-radius: 20px;\n"
"background: None;")
        self.l_Icon_Description.setText("")
        self.l_Icon_Description.setObjectName("l_Icon_Description")
        self.Layout_Description_2.addWidget(self.l_Icon_Description, 0, 0, 1, 1)
        self.l_Time = QtWidgets.QLabel(self.Layout_Description)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_Time.sizePolicy().hasHeightForWidth())
        self.l_Time.setSizePolicy(sizePolicy)
        self.l_Time.setStyleSheet("background: None;")
        self.l_Time.setObjectName("l_Time")
        self.Layout_Description_2.addWidget(self.l_Time, 0, 3, 1, 1)
        self.l_Description = QtWidgets.QLabel(self.Layout_Description)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_Description.sizePolicy().hasHeightForWidth())
        self.l_Description.setSizePolicy(sizePolicy)
        self.l_Description.setStyleSheet("background: None;")
        self.l_Description.setObjectName("l_Description")
        self.Layout_Description_2.addWidget(self.l_Description, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Layout_Description_2.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.Layout_Description, 2, 0, 1, 2)
        self.Main_2.addWidget(self.Header)
        self.Footer = QtWidgets.QWidget(self.Main)
        self.Footer.setStyleSheet("background: rgb(43,42,41);\n"
"border-bottom-right-radius: 60px;")
        self.Footer.setObjectName("Footer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Footer)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_History = QtWidgets.QTableWidget(self.Footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.l_History.sizePolicy().hasHeightForWidth())
        self.l_History.setSizePolicy(sizePolicy)
        self.l_History.setMinimumSize(QtCore.QSize(0, 200))
        self.l_History.setStyleSheet("background-color: rgb(23, 22, 21);\n"
"border-radius: 20px;")
        self.l_History.setObjectName("l_History")
        self.l_History.setColumnCount(0)
        self.l_History.setRowCount(0)
        self.verticalLayout.addWidget(self.l_History)
        self.l_Input_ID = QtWidgets.QTextEdit(self.Footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.l_Input_ID.sizePolicy().hasHeightForWidth())
        self.l_Input_ID.setSizePolicy(sizePolicy)
        self.l_Input_ID.setMinimumSize(QtCore.QSize(0, 40))
        self.l_Input_ID.setStyleSheet("background-color: rgb(23, 22, 21);\n"
"border-bottom:2px solid rgba(255, 255, 255, 100);\n"
"border-radius: 10px;")
        self.l_Input_ID.setObjectName("l_Input_ID")
        self.verticalLayout.addWidget(self.l_Input_ID)
        self.Main_2.addWidget(self.Footer)
        self.MainWindow_2.addWidget(self.Main)
        MainWindow.setCentralWidget(self.MainApps)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Counter Cards"))
        self.l_Name.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Name Surname</span></p></body></html>"))
        self.l_Result.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">Result</span></p></body></html>"))
        self.l_Title.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt; color:#ffffff;\">Столовая <br/></span><span style=\" font-size:12pt; font-weight:600; text-decoration: underline; color:#ffffff;\">АО &quot;АзияАгроФуд&quot;</span></p></body></html>"))
        self.l_CounterUsers.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Количество посетителей: ????</span></p></body></html>"))
        self.l_Status.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt; font-weight:600; color:#11ff4c;\">Status</span></p></body></html>"))
        self.l_Time.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\">Время</span></p></body></html>"))
        self.l_Description.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Поднесите свой рабочий пропуск к считывателю.</span><span style=\" font-size:12pt; color:#ffffff;\"><br/>После писка, будет выписан один обед в столовой.</span></p></body></html>"))
        self.l_Input_ID.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:10px;\"><span style=\" font-size:14pt; color:#ffffff;\">Поднесите пропуск к прокси считывателю.</span></p></body></html>"))

if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())